### ISSUE TITLE
Possible solutions for react-router + navigating links with querystring params 

### ISSUE THREAD

**Issue by tsufiev** [spotify/redux-location-state#29]
First, I admit that the issue title doesn't look like it belongs to this repository :). It would be much more appropriate to post it in react-router issues, however this issue was raised many times, the react-router v4 (RRV4) way is summarised at https://github.com/ReactTraining/react-router/issues/6442 - so I've been thinking that the issue of routing links with querystring params could be handled by the means of redux-location-state (RLS). Okay, now going directly to the problem at hand.

In our application we have both RRV4 and RLS, and everything works fine until we need to navigate to url like '/components/tablets?id=some-id' while remaining in the same tab and not reloading the whole app from scratch. In RRV4 in order to properly navigate you have to use hierarchical links without query params, parsing of query strings is not supported out-of-the box. However for url like ours above we cannot use hierarchical link because '/tablets?id=some-id' is not the permanent url, but rather a page with id filter applied. In other words, we want to navigate from one page to another and then apply a filter on it. 

It works fine when we open link in another tab, because mapLocationToState fires in that case and we have already configured all state & params mappings. It works well the opposite way - I mean the url gets properly updated when we update the filter on that page. The only way that doesn't work for us is navigating from one page to another + filter :(.

But then I thought: wait, we're listening for every history change and then dispatching an action inside RLS! Could it be our solution? So far LOCATION_PUSH action is dispatched without any payload. What if RLS dispatched this action with history.location as well - so our client app could process that action in one of its own reducers, what do you think?

P.S. I do not fully understand current use case for LOCATION_PUSH in RLS because it isn't used anywhere but the place where it's dispatched, so it seemed proper to clarify its purpose before suggesting a change.

**Comment by joshbDev** [comment]
I think I see where you're getting at. You have links with query params coded, so that you can update your redux values by using the different values in the parameters. Using something like `LOCATION_PUSH` would be correct for this. This functionality isn't built into RLS for a couple of reasons though, the biggest being that whenever the redux store updates `LOCATION_PUSH` gets fired because it's doing a `history.push` function, so you would have to write logic to say "ok, the url has changed so update the redux store with this new logic, otherwise if we're on the same page and have a LOCATION_PUSH, its RLS doing the update and don't do anything". 

The original data flow idea for RLS is that when the application state updates, the URL updates, but when the user uses the browser back or forward button then update the redux store to where the user navigated, so this kind of goes around that, but I can see the use case. I would caution a bit against this approach though, since your going outside of the standard redux lifecycle (action, middleware) for your SPA. Just something to think about.

I don't see the harm at all with appending the payload on the `LOCATION_PUSH` action, so I'll add that in. What you'll need to do though is manually write the middleware (see https://github.com/spotify/redux-location-state/blob/master/src/createReduxLocationActions.js#L49, but be sure to do the checking I mentioned above). Hopefully this is helpful.

**Comment by tsufiev** [comment]
Thank you, that should be enough for our use case!

**Comment by joshbDev** [comment]
ok 2.4.0 should have it!

**Comment by tsufiev** [comment]
Yay \o/

**Comment by ghost1face** [comment]
Hey all, I know this issue is closed but was curious if @tsufiev, how did you go about solving your problem?  I just ran into the same today and have two approaches:

1. Dispatch an action to update redux state, then navigate to the new location which would then build the querystring from state
2. Navigate to a new path with query and similar to @joshbDev 's feedback create custom middleware to handle accordingly.  

#2 seems to be the most straightforward for a growing team, #1 is the more declarative approach but not necessarily straight forward.

Just curious to which route you ended up taking @tsufiev ?

**Comment by tsufiev** [comment]
@ghost1face, we took the 2nd path, since it was exactly what we needed - to update the state based on query parameters on links we navigated to.

![Screenshot from 2019-03-28 17-03-10](https://user-images.githubusercontent.com/1240006/55163799-7f4b9d80-517b-11e9-8683-273d1c9c8bc6.png)
